#!/usr/bin/env bash
set -euo pipefail
shopt -s failglob
shopt -s globstar

iscmd() {
	command -v "$1" >/dev/null
}

anyfiles() {
	find . -type f -name "*.$1" -print -quit | grep -q .
}

if iscmd nix && anyfiles "nix"; then
	(
		set -x
		nix fmt ./**/*.nix
	)
fi

if iscmd gdscript-formatter && anyfiles "gd"; then
	(
		set -x
		gdscript-formatter ./**/*.gd
	)
fi
